CREATE TYPE COURIER_STATUS AS ENUM (
    'AVAILABLE', --müsait
    'BUSY', --meşgul(teslimatta)
    'OFF_DUTY', --izinli
    'ON_LEAVE', --ayrıldı
    'SUSPENDED' --askıya alındı
);

CREATE TYPE PACKAGE_STATUS AS ENUM (
    'CREATED', --kayıt açıldı henüz şubeye teslim edilmedi.
    'RECEIVED_AT_BRANCH', --kargo şubeye verildi.
    'IN_TRANSIT', --transfer aşamasında
    'ARRIVED_DESTINATION', --teslimat şubesine ulaşıldı
    'OUT_FOR_DELIVERY',
    'DELIVERED',
    'DELIVERY_FAILED',
	'RETURNING', --iade olarak işaretlendi
    'RETURNED' --iade tamamlandı
);

CREATE TYPE DELIVERY_STATUS AS ENUM (
    'ASSIGNED', --planlanan(kuryeden onay beklenir)
    'IN_PROGRESS', --aktif teslimat(kurye onayladıktan sonrasında işleme geçer)
    'COMPLETED',
    'FAILED', --başarısız(adreste kimse yok vs. tekrar denenecek ise)
    'CANCELLED' --iptal
);

CREATE TYPE INVOICE_STATUS AS ENUM (
    'ISSUED', --fatura kesildi, ödeme bekleniyor
    'PAID',
    'CANCELLED',
    'REFUNDED'
);

CREATE TYPE PAYMENT_STATUS AS ENUM (
    'PENDING',
    'SUCCESS',
    'FAILED',
    'REFUNDED'
);

CREATE TYPE PACKAGE_TYPE AS ENUM (
    'STANDARD',
    'FRAGILE', --kırılabilir
    'LIQUID', --sıvı
    'ELECTRONIC',
    'GLASS',
    'FOOD' --gıda
);

CREATE TYPE EMPLOYEE_TYPE AS ENUM (
	'BRANCH_STAFF',
	'COURIER'
);

CREATE TYPE CUSTOMER_TYPE AS ENUM (
	'INDIVIDUAL_CUSTOMER',
	'CORPORATE_CUSTOMER'
);

CREATE TABLE ADDRESS (
	ADDRESS_ID SERIAL PRIMARY KEY,
	NEIGHBORHOOD VARCHAR(50),
	STREET VARCHAR(50),
	APARTMENT_NUMBER VARCHAR(6), -- 9999/A
	STATE VARCHAR(32),
	CITY VARCHAR(32), 
	COUNTRY VARCHAR(32), 
	ZIP VARCHAR(6) -- XXXXX veya YYYYYY sadece türkiye içinse CHAR(5)
);

CREATE TABLE BRANCH (
	BRANCH_ID SMALLSERIAL PRIMARY KEY,
	BRANCH_NAME VARCHAR(50) NOT NULL UNIQUE, --İstanbul Avcılar Merkez Şubesi
	BRANCH_PHONE VARCHAR(15) NOT NULL, -- +90 555 444 33 22 maks 15 basamak
	BRANCH_ADDRESS_ID INTEGER NOT NULL UNIQUE,

	CONSTRAINT FK_BRANCH_ADDRESS
		FOREIGN KEY (BRANCH_ADDRESS_ID)
		REFERENCES ADDRESS(ADDRESS_ID)
);

CREATE TABLE EMPLOYEE (
	EMPLOYEE_ID SERIAL PRIMARY KEY,
	FIRST_NAME VARCHAR(32) NOT NULL,
	LAST_NAME VARCHAR(32) NOT NULL,
	SSN VARCHAR(16) NOT NULL UNIQUE, --türkiye için 11 CHAR(11)
	BRANCH_ID SMALLINT,
	TYPE EMPLOYEE_TYPE,

	CONSTRAINT FK_EMPLOYEE_BRANCH
		FOREIGN KEY (BRANCH_ID)
		REFERENCES BRANCH(BRANCH_ID)
);

CREATE TABLE COURIER (
	EMPLOYEE_ID INT PRIMARY KEY,
	DRIVER_LICENSE TEXT NOT NULL,
	STATUS COURIER_STATUS,

	CONSTRAINT FK_COURIER_EMPLOYEE
		FOREIGN KEY (EMPLOYEE_ID)
		REFERENCES EMPLOYEE(EMPLOYEE_ID)
);

CREATE TABLE BRANCH_STAFF (
	EMPLOYEE_ID INT PRIMARY KEY,
	ROLE VARCHAR(16),

	CONSTRAINT FK_BRANCH_STAFF_EMPLOYEE
		FOREIGN KEY (EMPLOYEE_ID)
		REFERENCES EMPLOYEE(EMPLOYEE_ID)
);

CREATE TABLE CUSTOMER (
	CUSTOMER_ID SERIAL PRIMARY KEY,
	PHONE VARCHAR(13) NOT NULL UNIQUE,
	EMAIL VARCHAR(100) UNIQUE,
	TYPE CUSTOMER_TYPE NOT NULL
);

CREATE TABLE INDIVIDUAL_CUSTOMER (
	CUSTOMER_ID INT PRIMARY KEY,
	FIRST_NAME VARCHAR(100) NOT NULL,
	LAST_NAME VARCHAR(100) NOT NULL,
	SEX VARCHAR(6), -- female ya da male
	SSN VARCHAR(16) UNIQUE,
	BIRTH_DATE DATE,

	CONSTRAINT FK_INDIVIDUAL_CUSTOMER
		FOREIGN KEY (CUSTOMER_ID)
		REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE CORPORATE_CUSTOMER (
	CUSTOMER_ID INT PRIMARY KEY,
	CORPORATE_NAME VARCHAR(100), -- şirket adı uzun olabilir 100 kalsın
	TAX_ID VARCHAR(10),

	CONSTRAINT FK_CORPORATE_CUSTOMER
		FOREIGN KEY (CUSTOMER_ID)
		REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE HAS_ADDRESS (
	CUSTOMER_ID INT NOT NULL,
	ADDRESS_ID INT NOT NULL UNIQUE,
	ADDRESS_TITLE VARCHAR(20),

	CONSTRAINT FK_HAS_ADDRESS_CUSTOMER
		FOREIGN KEY (CUSTOMER_ID) 
		REFERENCES CUSTOMER(CUSTOMER_ID),

	CONSTRAINT FK_HAS_ADDRESS_ADDRESS
		FOREIGN KEY (ADDRESS_ID) 
		REFERENCES ADDRESS(ADDRESS_ID)
);

CREATE TABLE SHIPMENT (
	TRACKING_NUMBER CHAR(12) PRIMARY KEY, --TRXXXXXXXXXX max 10 mr gönderi
	CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
	SENDER_ADDRESS_ID INT,
	RECEIVER_ADDRESS_ID INT NOT NULL,
	CUSTOMER_ID INT NOT NULL,
	RECEIVER_ID INT NOT NULL, -- alıcının adı, soyadı ve numarası not null.

	CONSTRAINT FK_SHIPMENT_SENDER_ADDRESS
		FOREIGN KEY (SENDER_ADDRESS_ID)
		REFERENCES ADDRESS(ADDRESS_ID),

	CONSTRAINT FK_SHIPMENT_RECEIVER_ADDRESS
		FOREIGN KEY (RECEIVER_ADDRESS_ID)
		REFERENCES ADDRESS(ADDRESS_ID),

	CONSTRAINT FK_SHIPMENT_CUSTOMER
		FOREIGN KEY (CUSTOMER_ID)
		REFERENCES CUSTOMER(CUSTOMER_ID),

	CONSTRAINT FK_SHIPMENT_RECEIVER
		FOREIGN KEY (RECEIVER_ID)
		REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE PACKAGE (
	PACKAGE_BARCODE CHAR(14) PRIMARY KEY, --PKGXXXXXXXXXXX 100mr paket
	TYPE PACKAGE_TYPE DEFAULT 'STANDARD',
	WEIGHT DECIMAL(4,2) NOT NULL CHECK (WEIGHT > 0), --kg (99.99)
	HEIGHT DECIMAL(5,2) NOT NULL CHECK (HEIGHT > 0), --cm (999.99)
	WIDTH DECIMAL(5,2) NOT NULL CHECK (WIDTH > 0), --cm (999.99)
	LENGTH DECIMAL(5,2) NOT NULL CHECK (LENGTH > 0), --cm (999.99)
	TRACKING_NUMBER CHAR(12) NOT NULL, --bir gönderide bir çok paket bulunabilir
	BRANCH_ID SMALLINT, --çıktığı şube
	STATUS PACKAGE_STATUS DEFAULT 'CREATED',

	CONSTRAINT FK_PACKAGE_SHIPMENT
		FOREIGN KEY (TRACKING_NUMBER)
		REFERENCES SHIPMENT(TRACKING_NUMBER),
		
	CONSTRAINT FK_PACKAGE_BRANCH
		FOREIGN KEY (BRANCH_ID)
		REFERENCES BRANCH(BRANCH_ID)
);

CREATE TABLE TRACKING_LOG (
	LOG_ID BIGSERIAL PRIMARY KEY,
	LOG_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
	STATUS PACKAGE_STATUS NOT NULL,
	BRANCH_ID SMALLINT,
	PACKAGE_BARCODE CHAR(14) NOT NULL,

	CONSTRAINT FK_TRACKING_LOG_BRANCH
		FOREIGN KEY (BRANCH_ID)
		REFERENCES BRANCH(BRANCH_ID),

	CONSTRAINT FK_TRACKING_LOG_PACKAGE
		FOREIGN KEY (PACKAGE_BARCODE)
		REFERENCES PACKAGE(PACKAGE_BARCODE)
);

CREATE TABLE VEHICLE (
	VEHICLE_ID SMALLSERIAL PRIMARY KEY,
	PLATE VARCHAR(12) NOT NULL UNIQUE, -- 34ABC0000
	MODEL VARCHAR(32) NOT NULL,
	VOLUME_CAPACITY DECIMAL(6,2) NOT NULL CHECK (VOLUME_CAPACITY > 0), --kg (9999.99)
	WEIGHT_CAPACITY DECIMAL(6,2) NOT NULL CHECK (WEIGHT_CAPACITY > 0), --kg (9999.99)
	CREATED_AT DATE NOT NULL DEFAULT NOW()
);

CREATE TABLE DELIVERY (
	DELIVERY_ID BIGSERIAL PRIMARY KEY,
	ASSIGNED_AT TIMESTAMP, --planlanan tarih
	DELIVERED_AT TIMESTAMP, --teslim edilen tarih
	STATUS DELIVERY_STATUS NOT NULL,
	COURIER_ID INT, --henüz atama olmadı
	VEHICLE_ID SMALLINT,

	CONSTRAINT FK_DELIVERY_COURIER
		FOREIGN KEY (COURIER_ID)
		REFERENCES COURIER(EMPLOYEE_ID),

	CONSTRAINT FK_DELIVERY_VEHICLE
		FOREIGN KEY (VEHICLE_ID)
		REFERENCES VEHICLE(VEHICLE_ID)
);

CREATE TABLE HAS_PACKAGE (
	DELIVERY_ID BIGINT NOT NULL,
	PACKAGE_BARCODE CHAR(14) NOT NULL,
	PRIMARY KEY (DELIVERY_ID, PACKAGE_BARCODE), --composite primary key aynı teslimatta aynı paketin tekrarlanmasını engelliyor.

	CONSTRAINT FK_HAS_PACKAGE_DELIVERY
		FOREIGN KEY (DELIVERY_ID)
		REFERENCES DELIVERY(DELIVERY_ID),

	CONSTRAINT FK_HAS_PACKAGE_PACKAGE
		FOREIGN KEY (PACKAGE_BARCODE)
		REFERENCES PACKAGE(PACKAGE_BARCODE)
);

CREATE TABLE INVOICE (
	INVOICE_NUMBER CHAR(14) PRIMARY KEY, -- INVXXXXXXXXXXX 100mr
	TRACKING_NUMBER CHAR(12) NOT NULL,
	INVOICE_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
	STATUS INVOICE_STATUS,
	TOTAL_PRICE DECIMAL(9, 2) NOT NULL CHECK (TOTAL_PRICE > 0), --X.XXX.XXX,YY mak 10m

	CONSTRAINT FK_INVOICE_SHIPMENT
		FOREIGN KEY (TRACKING_NUMBER)
		REFERENCES SHIPMENT(TRACKING_NUMBER)
);

CREATE TABLE PAYMENT (
	PAYMENT_ID BIGSERIAL PRIMARY KEY,
	METHOD VARCHAR(16) NOT NULL, --credit card, google pay vs
	INVOICE_NUMBER CHAR(14) NOT NULL,
	PAYMENT_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
	STATUS PAYMENT_STATUS,

	CONSTRAINT FK_PAYMENT_INVOICE
		FOREIGN KEY (INVOICE_NUMBER)
		REFERENCES INVOICE(INVOICE_NUMBER)
);