/*Test sorguları*/
SELECT * FROM ADDRESS;

SELECT * FROM BRANCH;
SELECT * FROM EMPLOYEE;
SELECT * FROM COURIER;
SELECT * FROM BRANCH_STAFF;
SELECT * FROM VEHICLE;

SELECT * FROM CUSTOMER;
SELECT * FROM CORPORATE_CUSTOMER;
SELECT * FROM INDIVIDUAL_CUSTOMER;
SELECT * FROM HAS_ADDRESS;

SELECT * FROM SHIPMENT;
SELECT * FROM PACKAGE;
SELECT * FROM HAS_PACKAGE;
SELECT * FROM DELIVERY;
SELECT * FROM TRACKING_LOG;
SELECT * FROM INVOICE;
SELECT * FROM PAYMENT;


/*statuslarına göre paket durumları*/
SELECT STATUS, COUNT(*) AS TOTAL_PACKAGES
FROM PACKAGE
GROUP BY STATUS
ORDER BY TOTAL_PACKAGES DESC;

/*statuslarına göre teslimat durumları*/
SELECT STATUS, COUNT(*) AS TOTAL_DELIVERIES
FROM DELIVERY
GROUP BY STATUS
ORDER BY TOTAL_DELIVERIES DESC;

/*Statuslarına göre faturaların sıralaması*/
SELECT STATUS, COUNT(*) AS TOTAL_INVOICE
FROM INVOICE 
GROUP BY STATUS 
ORDER BY TOTAL_INVOICE DESC;

/*Tüm çalışanların cinsiyet sayısı*/
SELECT SEX, COUNT(*) AS CLIENT_COUNT
FROM INDIVIDUAL_CUSTOMER
GROUP BY SEX;

/*Shipmentların barcode'u*/
SELECT S.TRACKING_NUMBER, S.CREATED_AT, P.PACKAGE_BARCODE, P.STATUS
FROM SHIPMENT S
JOIN PACKAGE P ON P.TRACKING_NUMBER = S.TRACKING_NUMBER;

/*Bir shipment'a ait tüm gönderiler.*/
SELECT S.TRACKING_NUMBER, COUNT(P.PACKAGE_BARCODE) AS PACKAGE_COUNT
FROM SHIPMENT S
LEFT JOIN PACKAGE P ON P.TRACKING_NUMBER = S.TRACKING_NUMBER
GROUP BY S.TRACKING_NUMBER;

/*Müşterilerin adı soyadı ve yaşadığı şehire ait VIEW*/
CREATE VIEW VW_CUSTOMER_LOCATIONS AS
SELECT IC.FIRST_NAME, IC.LAST_NAME, A.CITY
FROM INDIVIDUAL_CUSTOMER IC
JOIN CUSTOMER C ON IC.CUSTOMER_ID = C.CUSTOMER_ID
JOIN HAS_ADDRESS HA ON C.CUSTOMER_ID = HA.CUSTOMER_ID
JOIN ADDRESS A ON HA.ADDRESS_ID = A.ADDRESS_ID
ORDER BY A.CITY;

/*Şubelerde ki paket sayısı*/
SELECT B.BRANCH_NAME, COUNT(P.PACKAGE_BARCODE) AS PACKAGE_COUNT
FROM BRANCH B
JOIN PACKAGE P ON B.BRANCH_ID = P.BRANCH_ID
GROUP BY B.BRANCH_NAME
ORDER BY PACKAGE_COUNT DESC;

/*Ödeme yöntemlerine göre ciro dağılımı*/
SELECT P.METHOD, SUM(I.TOTAL_PRICE) AS TOTAL_REVENUE
FROM PAYMENT P
JOIN INVOICE I ON P.INVOICE_NUMBER = I.INVOICE_NUMBER
WHERE P.STATUS = 'SUCCESS'
GROUP BY P.METHOD
ORDER BY TOTAL_REVENUE DESC;

/*Kuryelerin toplam teslimatları*/
SELECT E.FIRST_NAME, E.LAST_NAME, COUNT(D.DELIVERY_ID) AS TOTAL_DELIVERIES
FROM DELIVERY D
JOIN COURIER C ON D.COURIER_ID = C.EMPLOYEE_ID
JOIN EMPLOYEE E ON C.EMPLOYEE_ID = E.EMPLOYEE_ID
WHERE D.STATUS = 'COMPLETED'
GROUP BY E.FIRST_NAME, E.LAST_NAME
ORDER BY TOTAL_DELIVERIES DESC;

/*Tüm teslim süresi*/
SELECT DELIVERY_ID, DELIVERED_AT - ASSIGNED_AT AS DELIVERY_DURATION
FROM DELIVERY
WHERE STATUS = 'COMPLETED';

/*500 TL üzeri faturalara %20 vergi*/
SELECT INVOICE_NUMBER, TOTAL_PRICE, TOTAL_PRICE * 1.20 AS PRICE_WITH_VAT
FROM INVOICE
WHERE TOTAL_PRICE > 500;

/*Ortalamadan yüksek ağırlığa sahip paketler*/
SELECT PACKAGE_BARCODE, WEIGHT
FROM PACKAGE
WHERE WEIGHT > (SELECT AVG(WEIGHT) FROM PACKAGE);

/*Ortalamadan yüksek faturaya sahip şirketler*/
SELECT CC.CORPORATE_NAME, I.TOTAL_PRICE
FROM INVOICE I
JOIN SHIPMENT S ON I.TRACKING_NUMBER = S.TRACKING_NUMBER
JOIN CORPORATE_CUSTOMER CC ON S.CUSTOMER_ID = CC.CUSTOMER_ID
WHERE I.TOTAL_PRICE > (SELECT AVG(TOTAL_PRICE) FROM INVOICE);

/*Hiç kargo göndermemiş müşteriler*/
SELECT C.CUSTOMER_ID, IC.FIRST_NAME, IC.LAST_NAME
FROM CUSTOMER C
JOIN INDIVIDUAL_CUSTOMER IC ON C.CUSTOMER_ID = IC.CUSTOMER_ID
LEFT JOIN SHIPMENT S ON C.CUSTOMER_ID = S.CUSTOMER_ID
WHERE S.TRACKING_NUMBER IS NULL;

/*Araçlara göre toplam taşınan yük(kg)*/
SELECT V.PLATE, SUM(P.WEIGHT) AS TOTAL_CARRIED_WEIGHT
FROM DELIVERY D
JOIN VEHICLE V ON D.VEHICLE_ID = V.VEHICLE_ID
JOIN HAS_PACKAGE HP ON D.DELIVERY_ID = HP.DELIVERY_ID
JOIN PACKAGE P ON HP.PACKAGE_BARCODE = P.PACKAGE_BARCODE
GROUP BY V.PLATE
ORDER BY TOTAL_CARRIED_WEIGHT DESC;

/*Paket tipine göre cirolar*/
SELECT P.TYPE, SUM(I.TOTAL_PRICE) AS REVENUE, COUNT(P.TYPE)
FROM PACKAGE P
JOIN SHIPMENT S ON P.TRACKING_NUMBER = S.TRACKING_NUMBER
JOIN INVOICE I ON S.TRACKING_NUMBER = I.TRACKING_NUMBER
GROUP BY P.TYPE;

/*Son 30 gün içinde teslim edilmemiş kargolar*/
SELECT S.TRACKING_NUMBER, P.STATUS, S.CREATED_AT
FROM SHIPMENT S
JOIN PACKAGE P ON S.TRACKING_NUMBER = P.TRACKING_NUMBER
WHERE S.CREATED_AT > NOW() - INTERVAL '1 days'
AND P.STATUS NOT IN ('DELIVERED', 'RETURNING', 'RETURNED');

/*En çok kargo gönderen ilk 3 kişi*/
SELECT C.EMAIL, COUNT(S.TRACKING_NUMBER) AS SHIPMENT_COUNT
FROM CUSTOMER C
JOIN SHIPMENT S ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY C.EMAIL
ORDER BY SHIPMENT_COUNT DESC
LIMIT 3;

/*En fazla fatura ödeyen ilk 5 kişi*/
SELECT C.TYPE, I.TOTAL_PRICE
FROM INVOICE I
JOIN SHIPMENT S ON I.TRACKING_NUMBER = S.TRACKING_NUMBER
JOIN CUSTOMER C ON S.CUSTOMER_ID = C.CUSTOMER_ID
ORDER BY I.TOTAL_PRICE DESC
LIMIT 5;


--1

SELECT * FROM INDIVIDUAL_CUSTOMER;
SELECT * FROM PACKAGE;
SELECT * FROM SHIPMENT;
SELECT * FROM ADDRESS;
SELECT * FROM HAS_ADDRESS;

SELECT FIRST_NAME, LAST_NAME, P.PACKAGE_BARCODE 
FROM INDIVIDUAL_CUSTOMER IC
JOIN HAS_ADDRESS HA ON HA.CUSTOMER_ID = IC.CUSTOMER_ID
JOIN ADDRESS A ON HA.ADDRESS_ID = A.ADDRESS_ID
JOIN SHIPMENT S ON S.CUSTOMER_ID = IC.CUSTOMER_ID
JOIN PACKAGE P ON S.TRACKING_NUMBER = P.TRACKING_NUMBER
WHERE A.CITY = 'Ankara'
AND P.STATUS = 'IN_TRANSIT';

--2

SELECT * FROM INVOICE;
SELECT * FROM PAYMENT;

SELECT P.METHOD, COUNT(P.PAYMENT_ID), SUM(INV.TOTAL_PRICE) AS TOTAL,
		ROUND((SUM(INV.TOTAL_PRICE) * 100.0) / SUM(SUM(INV.TOTAL_PRICE)) OVER(), 2) AS PERCENTAGE
FROM INVOICE INV
JOIN PAYMENT P ON P.INVOICE_NUMBER = INV.INVOICE_NUMBER
GROUP BY P.METHOD
ORDER BY TOTAL DESC;

--3

SELECT * FROM HAS_PACKAGE;
SELECT * FROM PACKAGE;

SELECT P.PACKAGE_BARCODE, P.TYPE
FROM PACKAGE P
LEFT JOIN HAS_PACKAGE HA ON HA.PACKAGE_BARCODE = P.PACKAGE_BARCODE
WHERE HA.PACKAGE_BARCODE IS NULL;

--4

SELECT * FROM CORPORATE_CUSTOMER;
SELECT * FROM SHIPMENT;
SELECT * FROM INVOICE;

SELECT CORPORATE_NAME, SUM(INV.TOTAL_PRICE) AS TOTAL_SPENT
FROM CORPORATE_CUSTOMER CC
JOIN SHIPMENT S ON S.CUSTOMER_ID = CC.CUSTOMER_ID
JOIN INVOICE INV ON INV.TRACKING_NUMBER = S.TRACKING_NUMBER
GROUP BY CC.CORPORATE_NAME
HAVING SUM(INV.TOTAL_PRICE) > 1500
ORDER BY TOTAL_SPENT DESC;

--5

SELECT * FROM DELIVERY;
SELECT * FROM EMPLOYEE;
SELECT * FROM TRACKING_LOG;

SELECT EMP.FIRST_NAME, EMP.LAST_NAME, D.DELIVERED_AT - D.ASSIGNED_AT AS TIME, D.DELIVERED_AT
FROM DELIVERY D
JOIN EMPLOYEE EMP ON EMP.EMPLOYEE_ID = D.COURIER_ID
WHERE D.DELIVERED_AT - D.ASSIGNED_AT < INTERVAL '1 HOUR' AND D.DELIVERED_AT - D.ASSIGNED_AT IS NOT NULL
ORDER BY TIME DESC;
