CREATE OR REPLACE FUNCTION LOG_PACKAGE_CHANGES() 
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO TRACKING_LOG (LOG_DATE, STATUS, BRANCH_ID, PACKAGE_BARCODE)
        VALUES (NOW(), NEW.STATUS, NEW.BRANCH_ID, NEW.PACKAGE_BARCODE);
    END IF;
	
    IF (TG_OP = 'UPDATE') THEN
        IF OLD.STATUS IS DISTINCT FROM NEW.STATUS THEN
            INSERT INTO TRACKING_LOG (LOG_DATE, STATUS, BRANCH_ID, PACKAGE_BARCODE)
            VALUES (NOW(), NEW.STATUS, NEW.BRANCH_ID, NEW.PACKAGE_BARCODE);
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS TRG_LOG_PACKAGE_CHANGES ON PACKAGE;

CREATE TRIGGER TRG_LOG_PACKAGE_CHANGES
AFTER INSERT OR UPDATE
ON PACKAGE
FOR EACH ROW
EXECUTE FUNCTION LOG_PACKAGE_CHANGES();