-- TRIGGER TEST 2(Status güncelleme)
INSERT INTO SHIPMENT (TRACKING_NUMBER, RECEIVER_ADDRESS_ID, CUSTOMER_ID, RECEIVER_ID)
VALUES ('TRG-TEST-3', 1, 1, 1);

INSERT INTO PACKAGE (
    PACKAGE_BARCODE, TRACKING_NUMBER, BRANCH_ID, STATUS, 
    WEIGHT, HEIGHT, WIDTH, LENGTH, TYPE
) VALUES (
    'PKG-TRG-3', 'TRG-TEST-3', 1, 'CREATED', 
    1.5, 10, 10, 10, 'STANDARD'
);

UPDATE PACKAGE 
SET STATUS = 'RECEIVED_AT_BRANCH' 
WHERE PACKAGE_BARCODE = 'PKG-TRG-3';

SELECT * FROM TRACKING_LOG 
WHERE PACKAGE_BARCODE = 'PKG-TRG-3';