CREATE OR REPLACE FUNCTION PROVIDE_ON_TIME_DELIVERY()
RETURNS TRIGGER AS $$
BEGIN
	UPDATE PACKAGE
    SET STATUS = 'RETURNING'
    FROM SHIPMENT
    WHERE PACKAGE.TRACKING_NUMBER = SHIPMENT.TRACKING_NUMBER
    AND PACKAGE.PACKAGE_BARCODE = NEW.PACKAGE_BARCODE 
    AND PACKAGE.STATUS NOT IN ('DELIVERED', 'RETURNING', 'RETURNED') --5 gün içinde gönderinin teslim/iade edilmediğinde iade eder
    AND NOW() - SHIPMENT.CREATED_AT > INTERVAL '5 days';

	IF FOUND THEN
        RAISE NOTICE 'Package % returning automatically (Exceeded 5-day limit)!', NEW.PACKAGE_BARCODE;
    END IF;
	
	UPDATE PACKAGE
	SET STATUS = 'RETURNING'
	WHERE PACKAGE_BARCODE = NEW.PACKAGE_BARCODE
	AND STATUS NOT IN ('DELIVERED', 'RETURNING', 'RETURNED')
	AND EXISTS (
		SELECT 1
		FROM TRACKING_LOG TL
		WHERE TL.PACKAGE_BARCODE = NEW.PACKAGE_BARCODE
		AND TL.STATUS = 'ARRIVED_DESTINATION' --son şubede 3 günden fazla beklerse geri gönderilir
		AND NOW() - TL.LOG_DATE > INTERVAL '3 days'
	);
	
	IF FOUND THEN
        RAISE NOTICE 'Package % returning automatically (Exceeded 3-day limit at branch)!', NEW.PACKAGE_BARCODE;
    END IF;
	
	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS TRG_PROVIDE_ON_TIME_DELIVERY ON TRACKING_LOG;

CREATE TRIGGER TRG_PROVIDE_ON_TIME_DELIVERY
AFTER INSERT OR UPDATE
ON TRACKING_LOG
FOR EACH ROW
EXECUTE FUNCTION PROVIDE_ON_TIME_DELIVERY();
