--TRIGGER TEST 1(5 günde teslim edilmeli)
INSERT INTO SHIPMENT (TRACKING_NUMBER, CREATED_AT, SENDER_ADDRESS_ID, RECEIVER_ADDRESS_ID, CUSTOMER_ID, RECEIVER_ID) 
VALUES (
    'TRG-TEST-1', 
    NOW() - INTERVAL '6 days', --6 gün öncesine bir gönderi oluştur
    1, 1, 1, 1
);

INSERT INTO PACKAGE (PACKAGE_BARCODE, TRACKING_NUMBER, BRANCH_ID, STATUS, WEIGHT, HEIGHT, WIDTH, LENGTH, TYPE)
VALUES (
    'PKG-TRG-1', 
    'TRG-TEST-1', 
    1, 'IN_TRANSIT',
    1, 10, 10, 10, 'STANDARD'
);

INSERT INTO TRACKING_LOG (LOG_DATE, STATUS, BRANCH_ID, PACKAGE_BARCODE)
VALUES (NOW(), 'IN_TRANSIT', 1, 'PKG-TRG-1');

SELECT PACKAGE_BARCODE, STATUS 
FROM PACKAGE 
WHERE PACKAGE_BARCODE = 'PKG-TRG-1';  --status returning olmalı



--TRIGGER TEST 1(3 günden fazla şubede bekleme)
INSERT INTO SHIPMENT (TRACKING_NUMBER, CREATED_AT, SENDER_ADDRESS_ID, RECEIVER_ADDRESS_ID, CUSTOMER_ID, RECEIVER_ID)
VALUES ('TRG-TEST-2', NOW(), 1, 1, 1, 1);

INSERT INTO PACKAGE (PACKAGE_BARCODE, TRACKING_NUMBER, BRANCH_ID, STATUS, WEIGHT, HEIGHT, WIDTH, LENGTH, TYPE)
VALUES (
    'PKG-TRG-2', 
    'TRG-TEST-2', 
    1, 'ARRIVED_DESTINATION', 
    1, 10, 10, 10, 'STANDARD'
);

INSERT INTO TRACKING_LOG (LOG_DATE, STATUS, BRANCH_ID, PACKAGE_BARCODE)
VALUES (
    NOW() - INTERVAL '4 days', --4 gün önce gelmiş
    'ARRIVED_DESTINATION', 
    1, 'PKG-TRG-2'
);

INSERT INTO TRACKING_LOG (LOG_DATE, STATUS, BRANCH_ID, PACKAGE_BARCODE)
VALUES (NOW(), 'OUT_FOR_DELIVERY', 1, 'PKG-TRG-2');

SELECT PACKAGE_BARCODE, STATUS FROM PACKAGE WHERE PACKAGE_BARCODE = 'PKG-TRG-2';